export const employeeData = [
  {
    id: 1,
    name: "Aman",
    department: "Engineering",
    role: "Senior Developer",
    manager: "Priya Singh",
    startDate: "2020-03-15",
    metrics: {
      productivity: 7,
      qualityOfWork: 92,
      teamwork: 85,
      communication: 78,
      leadership: 83,
      innovation: 90,
      problemSolving: 88,
    },
    projects: [
      {
        id: "P001",
        name: "Website Redesign",
        contribution: 90,
        onTime: true,
        complexity: 8,
      },
      {
        id: "P002",
        name: "API Integration",
        contribution: 85,
        onTime: true,
        complexity: 9,
      },
      {
        id: "P003",
        name: "Database Optimization",
        contribution: 92,
        onTime: false,
        complexity: 7,
      },
    ],
    goals: [
      {
        id: "G001",
        description: "Complete Advanced React Course",
        status: "Completed",
        priority: "High",
      },
      {
        id: "G002",
        description: "Mentor junior developers",
        status: "In Progress",
        priority: "Medium",
      },
      {
        id: "G003",
        description: "Learn GraphQL",
        status: "Not Started",
        priority: "Low",
      },
    ],
    reviews: [
      {
        quarter: "Q1",
        year: 2023,
        score: 4.2,
        strengths: ["Technical skills", "Problem solving"],
        improvements: ["Communication", "Documentation"],
      },
      {
        quarter: "Q2",
        year: 2023,
        score: 4.5,
        strengths: ["Technical skills", "Problem solving", "Communication"],
        improvements: ["Documentation"],
      },
      {
        quarter: "Q3",
        year: 2023,
        score: 4.7,
        strengths: [
          "Technical skills",
          "Problem solving",
          "Communication",
          "Documentation",
        ],
        improvements: [],
      },
    ],
    skills: [
      { name: "JavaScript", level: 95, years: 8 },
      { name: "React", level: 92, years: 6 },
      { name: "Node.js", level: 88, years: 5 },
      { name: "SQL", level: 80, years: 7 },
      { name: "TypeScript", level: 85, years: 4 },
    ],
  },
  {
    id: 2,
    name: "Naman",
    department: "Engineering",
    role: "Full Stack Developer",
    manager: "Priya Singh",
    startDate: "2021-06-10",
    metrics: {
      productivity: 82,
      qualityOfWork: 88,
      teamwork: 90,
      communication: 85,
      leadership: 75,
      innovation: 80,
      problemSolving: 87,
    },
    projects: [
      {
        id: "P002",
        name: "API Integration",
        contribution: 78,
        onTime: true,
        complexity: 9,
      },
      {
        id: "P004",
        name: "Mobile App Development",
        contribution: 85,
        onTime: true,
        complexity: 8,
      },
    ],
    goals: [
      {
        id: "G004",
        description: "Learn AWS",
        status: "In Progress",
        priority: "High",
      },
      {
        id: "G005",
        description: "Improve UI/UX skills",
        status: "In Progress",
        priority: "Medium",
      },
    ],
    reviews: [
      {
        quarter: "Q2",
        year: 2023,
        score: 4.0,
        strengths: ["Teamwork", "Communication"],
        improvements: ["Technical depth", "Time management"],
      },
      {
        quarter: "Q3",
        year: 2023,
        score: 4.2,
        strengths: ["Teamwork", "Communication", "Technical skills"],
        improvements: ["Time management"],
      },
    ],
    skills: [
      { name: "JavaScript", level: 88, years: 5 },
      { name: "React", level: 85, years: 4 },
      { name: "Node.js", level: 82, years: 3 },
      { name: "CSS", level: 90, years: 6 },
      { name: "MongoDB", level: 75, years: 2 },
    ],
  },
  {
    id: 3,
    name: "Kenny",
    department: "Product",
    role: "Product Manager",
    manager: "Sarah Williams",
    startDate: "2019-08-22",
    metrics: {
      productivity: 90,
      qualityOfWork: 92,
      teamwork: 94,
      communication: 95,
      leadership: 88,
      innovation: 86,
      problemSolving: 89,
    },
    projects: [
      {
        id: "P001",
        name: "Website Redesign",
        contribution: 75,
        onTime: true,
        complexity: 8,
      },
      {
        id: "P004",
        name: "Mobile App Development",
        contribution: 92,
        onTime: false,
        complexity: 8,
      },
      {
        id: "P005",
        name: "Customer Feedback System",
        contribution: 94,
        onTime: true,
        complexity: 7,
      },
    ],
    goals: [
      {
        id: "G006",
        description: "Improve user research methodology",
        status: "Completed",
        priority: "High",
      },
      {
        id: "G007",
        description: "Develop stakeholder management skills",
        status: "Completed",
        priority: "High",
      },
      {
        id: "G008",
        description: "Learn data analytics",
        status: "In Progress",
        priority: "Medium",
      },
    ],
    reviews: [
      {
        quarter: "Q1",
        year: 2023,
        score: 4.5,
        strengths: ["Communication", "Leadership", "User focus"],
        improvements: ["Technical knowledge"],
      },
      {
        quarter: "Q2",
        year: 2023,
        score: 4.6,
        strengths: ["Communication", "Leadership", "User focus"],
        improvements: ["Technical knowledge"],
      },
      {
        quarter: "Q3",
        year: 2023,
        score: 4.8,
        strengths: [
          "Communication",
          "Leadership",
          "User focus",
          "Technical knowledge",
        ],
        improvements: [],
      },
    ],
    skills: [
      { name: "Product Management", level: 95, years: 6 },
      { name: "User Research", level: 90, years: 5 },
      { name: "Agile Methodologies", level: 92, years: 7 },
      { name: "Market Analysis", level: 88, years: 4 },
      { name: "Wireframing", level: 85, years: 5 },
    ],
  },
  {
    id: 4,
    name: "David",
    department: "Engineering",
    role: "QA Engineer",
    manager: "Priya Singh",
    startDate: "2022-01-15",
    metrics: {
      productivity: 84,
      qualityOfWork: 90,
      teamwork: 82,
      communication: 76,
      leadership: 70,
      innovation: 72,
      problemSolving: 85,
    },
    projects: [
      {
        id: "P001",
        name: "Website Redesign",
        contribution: 65,
        onTime: true,
        complexity: 8,
      },
      {
        id: "P004",
        name: "Mobile App Development",
        contribution: 75,
        onTime: true,
        complexity: 8,
      },
    ],
    goals: [
      {
        id: "G009",
        description: "Learn automated testing frameworks",
        status: "Completed",
        priority: "High",
      },
      {
        id: "G010",
        description: "Improve bug documentation",
        status: "In Progress",
        priority: "Medium",
      },
    ],
    reviews: [
      {
        quarter: "Q2",
        year: 2023,
        score: 3.8,
        strengths: ["Attention to detail", "Problem identification"],
        improvements: ["Communication", "Proactivity"],
      },
      {
        quarter: "Q3",
        year: 2023,
        score: 4.0,
        strengths: [
          "Attention to detail",
          "Problem identification",
          "Testing thoroughness",
        ],
        improvements: ["Communication"],
      },
    ],
    skills: [
      { name: "Manual Testing", level: 95, years: 3 },
      { name: "Automated Testing", level: 80, years: 1 },
      { name: "TestRail", level: 90, years: 3 },
      { name: "JIRA", level: 85, years: 2 },
      { name: "SQL", level: 75, years: 2 },
    ],
  },
  {
    id: 5,
    name: "Sarah",
    department: "Design",
    role: "UI/UX Designer",
    manager: "Lisa Brown",
    startDate: "2020-11-05",
    metrics: {
      productivity: 88,
      qualityOfWork: 94,
      teamwork: 85,
      communication: 89,
      leadership: 80,
      innovation: 92,
      problemSolving: 86,
    },
    projects: [
      {
        id: "P001",
        name: "Website Redesign",
        contribution: 95,
        onTime: true,
        complexity: 8,
      },
      {
        id: "P004",
        name: "Mobile App Development",
        contribution: 92,
        onTime: true,
        complexity: 8,
      },
      {
        id: "P006",
        name: "Brand Refresh",
        contribution: 98,
        onTime: true,
        complexity: 9,
      },
    ],
    goals: [
      {
        id: "G011",
        description: "Master Figma advanced features",
        status: "Completed",
        priority: "High",
      },
      {
        id: "G012",
        description: "Learn motion design",
        status: "In Progress",
        priority: "Medium",
      },
      {
        id: "G013",
        description: "Improve user research skills",
        status: "Not Started",
        priority: "Low",
      },
    ],
    reviews: [
      {
        quarter: "Q1",
        year: 2023,
        score: 4.4,
        strengths: ["Visual design", "User-centered thinking"],
        improvements: ["Presenting to stakeholders"],
      },
      {
        quarter: "Q2",
        year: 2023,
        score: 4.6,
        strengths: ["Visual design", "User-centered thinking", "Collaboration"],
        improvements: ["Presenting to stakeholders"],
      },
      {
        quarter: "Q3",
        year: 2023,
        score: 4.7,
        strengths: [
          "Visual design",
          "User-centered thinking",
          "Collaboration",
          "Stakeholder management",
        ],
        improvements: [],
      },
    ],
    skills: [
      { name: "Figma", level: 95, years: 4 },
      { name: "UI Design", level: 92, years: 5 },
      { name: "UX Research", level: 85, years: 3 },
      { name: "Adobe Creative Suite", level: 90, years: 6 },
      { name: "Prototyping", level: 88, years: 4 },
    ],
  },
];

export const projectData = [
  {
    id: "P007",
    name: "New Customer Portal",
    requiredSkills: ["JavaScript", "React"],
  },
  {
    id: "P008",
    name: "Internal Tools Upgrade",
    requiredSkills: ["Node.js", "SQL"],
  },
  {
    id: "P009",
    name: "Mobile App Phase 2",
    requiredSkills: ["React", "UI Design"],
  },
  {
    id: "P010",
    name: "Data Analytics Dashboard",
    requiredSkills: ["SQL", "JavaScript"],
  },
];
